### ISSUE TITLE
param() attempts to write to a private variable

### ISSUE THREAD

**Issue by ialarmedalien** [pierre-vigier/Dancer2-Session-CGISession#1]
My error log has a lot of messages like this:

`param(): attempt to write to private parameter at /path/perl5/lib/perl5/Dancer2/Session/CGISession.pm line 92.`

I haven't done any significant troubleshooting, but I guess it might be from trying to write these CGI::Session-specific session parameters:

```
  _SESSION_ATIME => "1442614512",
  _SESSION_CTIME => "1442612409",
  _SESSION_ID => "de0d83fd3105058c12c85542d2df363b",
  _SESSION_REMOTE_ADDR => "127.0.0.1",
```

**Comment by pierre-vigier** [comment]
Hi,

can i have a bit of context here, i never seen that issue. 
That error message appears at what time? when accessing the keyword session? for reading? writing?
Is it specific to any special parameter?
On what Perl version do you have that issue?

**Comment by jwilliams99** [comment]
Hi there.  I'm getting this error as well:

`param(): attempt to write to private parameter at /usr/local/share/perl/5.18.2/Dancer2/Session/CGISession.pm line 89.`

my code causing the error

`session 'history' => to_json( $history )`

a look into the CGI::Session code (http://cpansearch.perl.org/src/MARKSTOS/CGI-Session-4.48/lib/CGI/Session.pm) shows the error message is thrown when one attempts to update one of the internal CGI::Session variables _SESSION

```

        if ($name =~ m/^_SESSION_/) {

            carp "param(): attempt to write to private parameter";
            return undef;
        }
```

the code in Dancer2::Session::CGISession triggering the error:

```
sub _flush {
    my ( $class, $id, $data ) = @_;

    my $cgi_session = $class->get_cgi_session( $id );
    $cgi_session->param( %{$data} );
    $cgi_session->param( %{$data} );

    $cgi_session->flush;
}
```

a Data::Dumper of $data

```
$VAR1 = {
          '_SESSION_REMOTE_ADDR' => '',
          '_SESSION_ATIME' => 1463718785,
          'history' => '[{"1":"2"},{"3":"4"},{"5":"6"}]',
          '_SESSION_CTIME' => 1463641753,
          '_SESSION_ID' => 'fb4ba53fa156772e78cef9c5467a700d',
          '_SESSION_ETIME' => undef
        };
```

i guess CGI::Session doesnt like updating the ^_SESSION.\* vars.  

Versions:

**Dancer**

```
package Dancer2;
# ABSTRACT: Lightweight yet powerful web application framework
$Dancer2::VERSION = '0.166001';
```

**CGISession**

```
package Dancer2::Session::CGISession;

use strict;
use 5.008_005;
our $VERSION = '0.02';
```

**Perl**
`This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi`

**Comment by jwilliams99** [comment]
I've created a pull request to fix this.

**Comment by pierre-vigier** [comment]
Hi, thanks, merged and uploaded to cpan

**Comment by jwilliams99** [comment]
whoa, that was quick! nice work :)
